services:
  fm-dx-webserver:
    image: ghcr.io/macsatcom/fm-dx-webserver:latest
    ports:
      - "8080:8080"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/snd:/dev/snd"
    volumes:
      - /run/udev:/run/udev:ro
    restart: unless-stopped
